local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#BBBDC3", bg = "#1F2023"},
Boolean = {fg = "#D08E6D"},
Character = {fg = "#D08E6D"},
ColorColumn = {bg = "#2C2D30"},
Comment = {fg = "#7A7E85"},
Conditional = {fg = "#D08E6D"},
Constant = {fg = "#C87EBA"},
CurSearch = {bg = "#114855"},
Cursor = {fg = "#000000", bg = "#CDCFD5"},
CursorLine = {bg = "#25272D"},
CursorLineFold = {},
CursorLineNr = {},
CursorLineSign = {},
Debug = {fg = "#7A7E85"},
Define = {fg = "#D08E6D"},
Delimiter = {},
DiagnosticError = {fg = "#F75565"},
DiffAdd = {fg = "#36DD4D"},
DiffChange = {fg = "#51A9FB"},
DiffDelete = {fg = "#F97784"},
DiffText = {bg = "#385570"},
Directory = {},
EndOfBuffer = {fg = "#1F2023", blend = 100},
Error = {fg = "#F75565"},
ErrorMsg = {fg = "#F75565"},
Exception = {fg = "#D08E6D"},
Float = {fg = "#2AABB7"},
FloatBorder = {fg = "#4E86BC"},
FloatTitle = {fg = "#BBBDC3", bg = "#1F2023"},
Function = {fg = "#56A8F5"},
Identifier = {fg = "#BBBDC3"},
Ignore = {fg = "#3D3F42"},
IncSearch = {bg = "#213B22"},
Include = {fg = "#D08E6D"},
Keyword = {fg = "#D08E6D"},
Label = {fg = "#D08E6D"},
LineNr = {fg = "#A0A3AB", bg = "#25272D"},
LineNrAbove = {fg = "#6B7280"},
LineNrBelow = {fg = "#6B7280"},
Macro = {fg = "#D08E6D"},
MatchParen = {bg = "#44464B"},
NonText = {fg = "#3D3F42"},
NormalFloat = {fg = "#BBBDC3"},
NormalNC = {bg = "#2C2D30"},
Number = {fg = "#2AABB7"},
Operator = {fg = "#D08E6D"},
Pmenu = {bg = "#2C2D30"},
PmenuSel = {bg = "#44464B"},
PreCondit = {fg = "#D08E6D"},
PreProc = {fg = "#D08E6D"},
Repeat = {fg = "#D08E6D"},
Search = {bg = "#213B22"},
SignColumn = {},
Special = {},
SpecialChar = {},
SpecialComment = {fg = "#7A7E85"},
SpecialKey = {fg = "#467C4D"},
SpellBad = {sp = "#69AB72", underline = true},
SpellCap = {},
SpellLocal = {},
SpellRare = {},
Statement = {fg = "#D08E6D"},
StatusLine = {bg = "#3E4656"},
StatusLineNC = {bg = "#2D333E"},
StorageClass = {fg = "#BBBDC3"},
String = {fg = "#69AB72"},
Structure = {fg = "#70AFBD"},
Substitute = {bg = "#213B22"},
Tag = {fg = "#D5B776"},
Title = {fg = "#D08E6D"},
Todo = {fg = "#1F2023", bg = "#BBBDC3"},
Type = {fg = "#BBBDC3"},
Typedef = {fg = "#70AFBD"},
Underlined = {fg = "#56A8F5", underline = true},
VertSplit = {fg = "#1F2023"},
Visual = {bg = "#214183"},
WarningMsg = {fg = "#F8C572"},
WildMenu = {},
WinBar = {bg = "#7A7E85"},
WinBarNC = {bg = "#1A1B1E"},
["@attribute"] = {fg = "#51A6BD"},
["@character.special"] = {},
["@constant"] = {fg = "#C87EBA"},
["@constant.builtin"] = {fg = "#C87EBA", bold = true},
["@constructor"] = {fg = "#D08E6D"},
["@field"] = {fg = "#C87EBA"},
["@function"] = {fg = "#56A8F5"},
["@function.builtin"] = {fg = "#56A8F5", bold = true},
["@function.method"] = {fg = "#B09C78"},
["@function.method.call"] = {fg = "#B09C78"},
["@method"] = {fg = "#B09C78"},
["@operator"] = {fg = "#BBBDC3"},
["@parameter"] = {fg = "#BBBDC3", italic = true},
["@property"] = {fg = "#C87EBA"},
["@punctuation"] = {fg = "#BBBDC3"},
["@punctuation.tag"] = {fg = "#D5B776"},
["@string.escape"] = {fg = "#D08E6D"},
["@tag"] = {fg = "#51A6BD"},
["@tag.attribute"] = {fg = "#BBBDC3"},
["@tag.builtin"] = {fg = "#D5B776"},
["@tag.delimiter"] = {fg = "#D5B776"},
["@type"] = {fg = "#70AFBD"},
["@type.builtin"] = {fg = "#D08E6D"},
["@type.definition"] = {fg = "#D08E6D"},
["@type.qualifier"] = {fg = "#D08E6D"},
["@variable"] = {fg = "#BBBDC3"},
["@variable.builtin"] = {fg = "#D08E6D"},
["@variable.member"] = {fg = "#C87EBA"},
["@variable.parameter"] = {italic = true},
["@variable.parameter.builtin"] = {fg = "#51A6BD"},
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='jeteyes'")

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
