local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#BBBDC3", bg = "#1F2023"},
Boolean = {fg = "#D08E6D"},
Character = {fg = "#D08E6D"},
ColorColumn = {bg = "#2C2D30"},
Comment = {fg = "#7A7E85"},
Conditional = {fg = "#D08E6D"},
Constant = {fg = "#C87EBA"},
CurSearch = {bg = "#114855"},
Cursor = {fg = "#000000", bg = "#CDCFD5"},
CursorLine = {bg = "#25272D"},
CursorLineFold = {},
CursorLineNr = {},
CursorLineSign = {},
Define = {fg = "#D08E6D"},
DiagnosticError = {fg = "#F75565"},
DiffAdd = {fg = "#36DD4D"},
DiffChange = {fg = "#51A9FB"},
DiffDelete = {fg = "#F97784"},
DiffText = {bg = "#385570"},
Directory = {},
EndOfBuffer = {fg = "#1F2023"},
Error = {fg = "#F75565"},
ErrorMsg = {fg = "#F75565"},
Exception = {fg = "#D08E6D"},
Float = {fg = "#2AABB7"},
FloatBorder = {fg = "#4E86BC"},
FloatTitle = {fg = "#BBBDC3", bg = "#1F2023"},
Function = {fg = "#56A8F5"},
Identifier = {fg = "#BBBDC3"},
IncSearch = {bg = "#213B22"},
Include = {fg = "#D08E6D"},
Keyword = {fg = "#D08E6D"},
Label = {fg = "#D08E6D"},
LineNr = {fg = "#A0A3AB", bg = "#25272D"},
LineNrAbove = {fg = "#6B7280"},
LineNrBelow = {fg = "#6B7280"},
Macro = {fg = "#D08E6D"},
MatchParen = {bg = "#44464B"},
NonText = {fg = "#56585D"},
NormalFloat = {fg = "#BBBDC3"},
NormalNC = {bg = "#2C2D30"},
Number = {fg = "#2AABB7"},
Operator = {fg = "#D08E6D"},
Pmenu = {bg = "#2C2D30"},
PmenuSel = {bg = "#44464B"},
PreCondit = {fg = "#D08E6D"},
PreProc = {fg = "#D08E6D"},
Repeat = {fg = "#D08E6D"},
Search = {bg = "#213B22"},
SignColumn = {},
Special = {},
SpecialChar = {},
SpecialKey = {fg = "#467C4D"},
SpellBad = {sp = "#69AB72", underline = true},
SpellCap = {},
SpellLocal = {},
SpellRare = {},
Statement = {fg = "#D08E6D"},
StatusLine = {bg = "#3E4656"},
StatusLineNC = {bg = "#2D333E"},
StorageClass = {fg = "#BBBDC3"},
String = {fg = "#69AB72"},
Structure = {fg = "#70AFBD"},
Substitute = {bg = "#213B22"},
Title = {fg = "#D08E6D"},
Todo = {fg = "#1F2023", bg = "#BBBDC3"},
Type = {fg = "#BBBDC3"},
Typedef = {fg = "#70AFBD"},
Visual = {bg = "#214183"},
WarningMsg = {fg = "#F75565"},
WildMenu = {},
WinBar = {bg = "#7A7E85"},
WinBarNC = {bg = "#1A1B1E"},
["@comment"] = {fg = "#7A7E85"},
["@constant"] = {fg = "#C87EBA"},
["@constructor"] = {fg = "#D08E6D"},
["@field"] = {fg = "#C87EBA"},
["@method"] = {fg = "#B09C78"},
["@parameter"] = {fg = "#BBBDC3", italic = true},
["@property"] = {fg = "#C87EBA"},
["@punctuation"] = {fg = "#BBBDC3"},
["@string.escape"] = {fg = "#D08E6D"},
["@text.literal"] = {fg = "#7A7E85"},
["@variable"] = {fg = "#BBBDC3"},
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='jeteyes'")

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
